# Generated by Django 6.0.3 on 2026-04-13 06:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedOutput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_js', models.TextField(blank=True)),
                ('routes', models.TextField(blank=True)),
                ('models_js', models.TextField(blank=True)),
                ('middleware', models.TextField(blank=True)),
                ('database_js', models.TextField(blank=True)),
                ('package_json', models.TextField(blank=True)),
                ('env_example', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('repository', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='output', to='uploader.uploadedrepository')),
            ],
        ),
    ]
