"""
Generates Oracle 23ai-compatible DDL from a SchemaIR object.
 
Output format:
  - One CREATE TABLE per table
  - GENERATED ALWAYS AS IDENTITY for auto fields
  - Inline CONSTRAINT for NOT NULL, UNIQUE
  - Separate ALTER TABLE ADD CONSTRAINT for FK references
  - CREATE INDEX for recommended indexes
"""
 
from apps.ir.schema import SchemaIR, TableSchema
 
 
def _col_ddl(col) -> str:
    parts = [f'  {col.name.upper():<30} {col.oracle_type}']
    if col.is_primary_key:
        parts.append('PRIMARY KEY')
    elif not col.is_nullable:
        parts.append('NOT NULL')
    if col.is_unique and not col.is_primary_key:
        parts.append('UNIQUE')
    # BooleanField CHECK constraint
    if 'NUMBER(1)' in col.oracle_type and not col.is_primary_key:
        parts.append('CHECK (VALUE IN (0, 1))')
    return ' '.join(parts)
 
 
def generate_oracle_ddl(schema_ir: SchemaIR) -> str:
    """
    Generates full Oracle DDL for all tables in SchemaIR.
    Returns a single string ready to run in SQL*Plus or Oracle APEX.
    """
    lines = []
    lines.append('-- ============================================================')
    lines.append('-- Oracle 23ai DDL generated by CodeMorph DB-AI')
    lines.append(f'-- Tables: {len(schema_ir.tables)}  |  '
                 f'Relationships: {len(schema_ir.relationship_edges)}')
    lines.append('-- ============================================================')
    lines.append('')
 
    fk_constraints = []     # collected for ALTER TABLE at the end
 
    for table in schema_ir.tables:
        tname = table.table_name.upper()
        lines.append(f'CREATE TABLE {tname} (')
 
        col_lines = [_col_ddl(col) for col in table.columns]
        lines.append(',\n'.join(col_lines))
        lines.append(');')
        lines.append('')
 
        # Collect FK constraints
        for fk in table.foreign_keys:
            if fk.relationship_type == 'ManyToManyField':
                # Generate junction table
                jt = f'{fk.from_table}_{fk.to_table}'.upper()
                lines.append(f'-- Junction table for {fk.from_table} <-> {fk.to_table} (ManyToMany)')
                lines.append(f'CREATE TABLE {jt} (')
                lines.append(f'  ID                             NUMBER(19) GENERATED ALWAYS AS IDENTITY PRIMARY KEY,')
                lines.append(f'  {fk.from_table.upper()}_ID    NUMBER(19) NOT NULL,')
                lines.append(f'  {fk.to_table.upper()}_ID      NUMBER(19) NOT NULL')
                lines.append(');')
                lines.append('')
            else:
                constraint_name = f'FK_{tname}_{fk.from_column.upper()}'
                fk_constraints.append(
                    f'ALTER TABLE {tname}\n'
                    f'  ADD CONSTRAINT {constraint_name}\n'
                    f'  FOREIGN KEY ({fk.from_column.upper()})\n'
                    f'  REFERENCES {fk.to_table.upper()}(ID)\n'
                    f'  ON DELETE {fk.on_delete};'
                )
 
    # FK constraints after all CREATE TABLEs (avoids ordering issues)
    if fk_constraints:
        lines.append('-- ── Foreign Key Constraints ──────────────────────────')
        lines.append('')
        lines.extend(fk_constraints)
        lines.append('')
 
    return '\n'.join(lines)
