# apps/generator/services/express_generator.py

from apps.ir.schema import RouteIR, RepositoryIR


def _generate_single_route(route: RouteIR) -> str:
    """
    Converts one RouteIR into an Express.js route string.
    
    For each HTTP method in the IR, we generate one Express route.
    
    Django:
        path('users/<int:pk>/', UserDetailView.as_view(), name='user-detail')
    
    IR:
        RouteIR(path='/users/:pk', methods=['GET'], view_name='UserDetailView')
    
    Express output:
        // Route: user-detail | View: UserDetailView
        router.get('/users/:pk', async (req, res) => {
          try {
            // TODO: implement UserDetailView logic
            res.json({ message: 'UserDetailView response' });
          } catch (error) {
            res.status(500).json({ error: error.message });
          }
        });
    """
    lines = []

    # Comment header for readability
    comment_parts = []
    if route.route_name:
        comment_parts.append(f"Route: {route.route_name}")
    if route.view_name:
        comment_parts.append(f"View: {route.view_name}")
    if comment_parts:
        lines.append(f"// {' | '.join(comment_parts)}")

    # Generate one Express route per HTTP method
    for method in route.methods:
        # Express method name is lowercase: GET→get, POST→post
        express_method = method.lower()

        # Build the route handler
        lines.append(
            f"router.{express_method}('{route.path}', async (req, res) => {{"
        )
        lines.append(f"  try {{")

        # If route has URL params, show how to access them
        if route.params:
            params_str = ', '.join([f'req.params.{p}' for p in route.params])
            lines.append(
                f"    // URL params: {params_str}"
            )

        # Placeholder implementation — real logic added in later iterations
        view_name = route.view_name or 'UnknownView'
        lines.append(
            f"    // TODO: implement {view_name} logic"
        )
        lines.append(
            f"    res.json({{ message: '{view_name} response' }});"
        )
        lines.append(f"  }} catch (error) {{")
        lines.append(
            f"    res.status(500).json({{ error: error.message }});"
        )
        lines.append(f"  }}")
        lines.append(f"}});")

    return '\n'.join(lines)


def generate_express_routes(repo_ir: RepositoryIR) -> str:
    """
    Converts a full RepositoryIR into a complete Express.js routes file.
    
    Takes all RouteIR objects and generates:
    1. File header with imports
    2. One router.method() call per route
    3. Module export
    
    Args:
        repo_ir: The RepositoryIR produced by the parser
        
    Returns:
        A string containing the complete Express.js routes file
    """

    lines = []

    # File header
    lines.append("// Auto-generated by CodeMorph")
    lines.append(f"// Source repo_id: {repo_ir.repo_id}")
    lines.append("// DO NOT EDIT — regenerate by re-running CodeMorph")
    lines.append("")
    lines.append("const express = require('express');")
    lines.append("const router = express.Router();")
    lines.append("")

    if not repo_ir.routes:
        lines.append("// No routes found in urls.py")
    else:
        for route in repo_ir.routes:
            lines.append(_generate_single_route(route))
            lines.append("")  # blank line between routes

    # Export the router
    lines.append("module.exports = router;")

    return '\n'.join(lines)