# apps/generator/services/middleware_generator.py

from apps.ir.schema import RepositoryIR


def generate_express_middleware(repo_ir: RepositoryIR) -> str:
    """
    Converts MiddlewareIR and AuthIR into a complete
    Express.js middleware setup file.

    Output structure:
    1. npm package imports
    2. app.use() calls for each middleware (in order)
    3. Auth middleware function
    4. Export

    Args:
        repo_ir: RepositoryIR with middleware and auth populated

    Returns:
        String containing the complete Express middleware file
    """
    lines = []

    # ── File header ───────────────────────────────────────────────────────────
    lines.append("// Auto-generated by CodeMorph")
    lines.append(f"// Source repo_id: {repo_ir.repo_id}")
    lines.append("// DO NOT EDIT — regenerate by re-running CodeMorph")
    lines.append("")

    # ── Collect unique npm packages needed ───────────────────────────────────
    packages = set()
    for mw in repo_ir.middleware:
        if mw.npm_package and mw.is_supported:
            packages.add(mw.npm_package)
    for auth in repo_ir.auth:
        if auth.npm_package and auth.is_supported:
            packages.add(auth.npm_package)

    # ── Generate require() imports ────────────────────────────────────────────
    lines.append("const express = require('express');")
    for package in sorted(packages):
        # Convert package name to valid JS variable
        # e.g. 'express-session' → 'session', 'jsonwebtoken' → 'jwt'
        var_name = _package_to_var_name(package)
        lines.append(f"const {var_name} = require('{package}');")

    lines.append("")
    lines.append("const app = express();")
    lines.append("")

    # ── Generate middleware setup ─────────────────────────────────────────────
    lines.append("// ── Middleware Setup ────────────────────────────────────")

    if not repo_ir.middleware:
        lines.append("// No middleware found in settings.py")
    else:
        # Sort by order to preserve Django middleware sequence
        sorted_middleware = sorted(repo_ir.middleware, key=lambda m: m.order)

        for mw in sorted_middleware:
            if mw.is_supported:
                lines.append(f"// {mw.django_class}")
                lines.append(f"app.use({mw.express_equivalent});")
            else:
                lines.append(f"// UNSUPPORTED: {mw.django_class}")
                lines.append(f"// {mw.express_equivalent}")
            lines.append("")

    # ── Generate auth middleware ──────────────────────────────────────────────
    if repo_ir.auth:
        lines.append("// ── Authentication ─────────────────────────────────────")
        lines.append("")

        for auth in repo_ir.auth:
            if auth.express_strategy == 'jwt':
                lines.extend(_generate_jwt_middleware(auth.npm_package))
            elif auth.express_strategy == 'session':
                lines.extend(_generate_session_auth_middleware())
            elif auth.express_strategy == 'basic':
                lines.extend(_generate_basic_auth_middleware())
            else:
                lines.append(f"// Custom auth: {auth.django_class}")
                lines.append(
                    f"// TODO: implement {auth.django_class} equivalent"
                )
            lines.append("")

    lines.append("module.exports = app;")
    return '\n'.join(lines)


def _package_to_var_name(package: str) -> str:
    """
    Converts an npm package name to a JS variable name.

    'express-session' → 'session'
    'jsonwebtoken'    → 'jwt'
    'helmet'          → 'helmet'
    'basic-auth'      → 'basicAuth'
    """
    name_map = {
        'express-session': 'session',
        'jsonwebtoken': 'jwt',
        'basic-auth': 'basicAuth',
        'passport-oauth2': 'oauth2',
    }
    return name_map.get(package, package.replace('-', '_'))


def _generate_jwt_middleware(npm_package: str) -> list:
    """Generates JWT authentication middleware."""
    return [
        "// JWT Authentication Middleware",
        "const authenticateToken = (req, res, next) => {",
        "  const authHeader = req.headers['authorization'];",
        "  const token = authHeader && authHeader.split(' ')[1];",
        "  if (!token) {",
        "    return res.status(401).json({ error: 'Access token required' });",
        "  }",
        "  jwt.verify(token, process.env.SECRET_KEY, (err, user) => {",
        "    if (err) {",
        "      return res.status(403).json({ error: 'Invalid or expired token' });",
        "    }",
        "    req.user = user;",
        "    next();",
        "  });",
        "};",
    ]


def _generate_session_auth_middleware() -> list:
    """Generates session-based authentication middleware."""
    return [
        "// Session Authentication Middleware",
        "const authenticateSession = (req, res, next) => {",
        "  if (req.session && req.session.userId) {",
        "    next();",
        "  } else {",
        "    res.status(401).json({ error: 'Authentication required' });",
        "  }",
        "};",
    ]


def _generate_basic_auth_middleware() -> list:
    """Generates basic authentication middleware."""
    return [
        "// Basic Authentication Middleware",
        "const authenticateBasic = (req, res, next) => {",
        "  const credentials = basicAuth(req);",
        "  if (!credentials) {",
        "    return res.status(401).json({ error: 'Basic auth required' });",
        "  }",
        "  // TODO: validate credentials against your user store",
        "  next();",
        "};",
    ]