# apps/generator/services/sequelize_generator.py

from apps.ir.schema import ModelIR, FieldIR, RepositoryIR


def _generate_field_definition(field: FieldIR) -> str:
    """
    Converts one FieldIR into a Sequelize field definition.

    Django:
        title = models.CharField(max_length=200, null=False)

    Sequelize output:
        title: {
          type: DataTypes.STRING(200),
          allowNull: false,
        },
    """
    lines = []
    lines.append(f"    {field.name}: {{")

    # Add max_length to STRING type if present
    if field.max_length and field.js_type == 'STRING':
        lines.append(f"      type: DataTypes.STRING({field.max_length}),")
    else:
        lines.append(f"      type: DataTypes.{field.js_type},")

    # allowNull maps from Django's null=True
    lines.append(f"      allowNull: {'true' if field.is_nullable else 'false'},")

    # Add default value if present
    if field.default is not None:
        # Wrap string defaults in quotes
        if field.default in ('True', 'False', 'None') or field.default.isdigit():
            js_default = field.default.lower().replace('none', 'null')
            lines.append(f"      defaultValue: {js_default},")
        else:
            lines.append(f"      defaultValue: '{field.default}',")

    lines.append(f"    }},")
    return '\n'.join(lines)


def _generate_single_model(model: ModelIR) -> str:
    """
    Converts one ModelIR into a complete Sequelize model definition.

    Django:
        class BlogPost(models.Model):
            title = models.CharField(max_length=200)
            body = models.TextField()

    Sequelize output:
        const BlogPost = sequelize.define('BlogPost', {
          title: {
            type: DataTypes.STRING(200),
            allowNull: false,
          },
          body: {
            type: DataTypes.TEXT,
            allowNull: false,
          },
        }, {
          tableName: 'blogpost',
          timestamps: true,
        });
    """
    lines = []

    # Model comment header
    lines.append(f"// Model: {model.name}")
    lines.append(f"const {model.name} = sequelize.define('{model.name}', {{")

    # Generate each field
    for field in model.fields:
        lines.append(_generate_field_definition(field))

    # Model options
    lines.append("}, {")
    lines.append(f"  tableName: '{model.table_name}',")
    lines.append(f"  timestamps: true,")
    lines.append("});")

    return '\n'.join(lines)


def generate_sequelize_models(repo_ir: RepositoryIR) -> str:
    """
    Converts all ModelIR objects in a RepositoryIR into a
    complete Sequelize models file.

    Args:
        repo_ir: The full RepositoryIR with models populated

    Returns:
        String containing the complete Sequelize models file
    """
    lines = []

    # File header
    lines.append("// Auto-generated by CodeMorph")
    lines.append(f"// Source repo_id: {repo_ir.repo_id}")
    lines.append("// DO NOT EDIT — regenerate by re-running CodeMorph")
    lines.append("")
    lines.append("const { DataTypes } = require('sequelize');")
    lines.append("const sequelize = require('../config/database');")
    lines.append("")

    if not repo_ir.models:
        lines.append("// No models found in models.py")
    else:
        for model in repo_ir.models:
            lines.append(_generate_single_model(model))
            lines.append("")

    # Export all models
    if repo_ir.models:
        model_names = ', '.join([m.name for m in repo_ir.models])
        lines.append(f"module.exports = {{ {model_names} }};")

    return '\n'.join(lines)