# Generated by Django 6.0.3 on 2026-04-08 07:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('uploader', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MigrationExperiment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experiment_name', models.CharField(max_length=100)),
                ('parser_version', models.CharField(default='v1', max_length=50)),
                ('generator_version', models.CharField(default='v1', max_length=50)),
                ('validator_version', models.CharField(default='v1', max_length=50)),
                ('total_routes_found', models.IntegerField(default=0)),
                ('routes_converted', models.IntegerField(default=0)),
                ('validation_passed', models.IntegerField(default=0)),
                ('conversion_accuracy', models.FloatField(default=0.0)),
                ('total_execution_ms', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('repository', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiments', to='uploader.uploadedrepository')),
            ],
        ),
    ]
